export const GET_DATA_START = 'GET_DATA_START';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED = ' GET_DATA_FAILED';
export const GET_DATA_STORE = 'GET_DATA_STORE';

export const GET_METADATA_START = 'GET_METADATA_START';
export const GET_METADATA_SUCCESS = 'GET_METADATA_SUCCESS';
export const GET_METADATA_FAILED = ' GET_METADATA_FAILED';
export const GET_METADATA_STORE = 'GET_METADATA_STORE';